---
- hosts: all 
  gather_facts: no
  become: yes
  tasks: 
  - name: Waiting for ssh
    wait_for_connection:
      timeout: 900
  - name: disable selinux
    selinux:
      state: disabled
  - name: load br_netfilter
    modprobe:
      name: br_netfilter
      state: present
  - name: iptables4/6 bridged traffic
    sysctl:
      name: "{{ item }}"
      value: '1'
      state: present
    with_items:
      - net.bridge.bridge-nf-call-ip6tables
      - net.bridge.bridge-nf-call-iptables
      - net.ipv4.ip_forward
  - name: Swap off
    shell: "swapoff -a"
  - name: Setup docker yum repo
    yum_repository:
      name: docker
      description: docker ce repo
      baseurl: https://download.docker.com/linux/centos/8/x86_64/stable
      enabled: yes
      gpgcheck: yes
      gpgkey: https://download.docker.com/linux/centos/gpg
  - name: Setup k8s yum repo
    yum_repository:
      name: kubernetes
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      description: kubernetes yum repo
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled: yes
  - name: Install kubernetes
    yum:
      name:
        - kubelet
        - kubeadm
        - kubectl
        - docker-ce
      state: present
  - name: enable docker
    systemd:
      name: docker
      enabled: yes
      state: started
  - name: enable kubelet
    systemd:
      name: kubelet
      enabled: yes
      state: started
- hosts: master
  gather_facts: no
  become: yes
  tasks:
  - name: firewall ports control plane
    ansible.posix.firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
      zone: public
      immediate: yes
    with_items:
      - 6443/tcp
      - 2379/tcp
      - 2380/tcp
      - 10250/tcp
      - 10251/tcp
      - 10252/tcp
  - name: firewall ports worker 
    ansible.posix.firewalld:
      rich_rule: "{{ item }}"
      permanent: true
      state: enabled
      zone: public
      immediate: yes
    with_items:
      - 'rule family=ipv4 source address=10.240.0.0/24 accept'
      - 'rule family=ipv4 source address=172.17.0.0/16 accept'
- hosts: worker
  gather_facts: no
  become: yes
  tasks:
  - name: firewall ports data plane
    ansible.posix.firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
      zone: public
      immediate: yes
    with_items:
      - 10250/tcp
     - 30000-32767/tcp


