- hosts: master
  gather_facts: no
  become: yes
  tags: kubeconfig
  tasks:
  - name: Fetching admin.conf
    tags: 
      - kubectl_fetch
    fetch:
      src: /etc/kubernetes/admin.conf
      dest: ~/.kube/config
      flat: yes
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Ensure the fqdn name of api
    lineinfile:
      path: ~/.kube/config
      regexp: '\s\s\s\sserver: https:\/\/10\.240\.0\.11:6443'
      line: '    server: https://cks.phartdoctor.us:6443'
  - name: Apply storage class
    shell: "kubectl apply -f deployments/gcp_pd_sc.yaml"
  - name: Apply dynamic pvc
    shell: "kubectl apply -f deployments/pvc_test.yaml"
  - name: Test nginx deployment
    shell: "kubectl apply -f deployments/nginx-deployment.yaml"
  - name: Add cert-manager
    tags: cert-manager
    shell: "kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml"
  - name: Add gcc secret
    tags: gcrsecret
    shell: kubectl create secret docker-registry regsecret --docker-server=gcr.io --docker-username=_json_key --docker-password="$(cat ~/.ssh/vmware-ysung.json)"
