- hosts: all
  gather_facts: no
  become: yes
  tags: cloud-config
  tasks:
  - name: Copy cloud-config
    copy:
      src: cloud-config
      dest: /etc/kubernetes/cloud-config
- hosts: master
  gather_facts: no
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
  - name: Kubeadm reset
    tags: reset
    shell: "kubeadm reset -f && rm -rf /etc/cni/net.d && iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X"
  - name: copy kubeadm-config
    copy:
      src: kubeadm.config
      dest: /tmp/
  - name: Kubeadm init
    tags: "init"
    shell: kubeadm init --upload-certs --config /tmp/kubeadm.config
- hosts: worker
  gather_facts: no
  become: yes
  tags: join
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
  - name: Kubeadm reset
    tags: reset
    shell: "kubeadm reset -f && rm -rf /etc/cni/net.d && iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X"
  - name: Generate join token
    shell: kubeadm token create --print-join-command
    register: join_command
    delegate_to: "{{ groups['master'][0] }}"
  - set_fact:
      kubeadm_join: "{{ join_command.stdout }}"
  - name: Run kubeadm join
    shell: "{{ kubeadm_join }}" 
- hosts: master
  gather_facts: no
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tags: kubeconfig
  tasks:
  - name: Install CNI
    tags: "init"
    #shell: "kubectl apply -f https://raw.githubusercontent.com/vmware-tanzu/antrea/master/build/yamls/antrea.yml"
    shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
    #shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
- hosts: master
  gather_facts: no
  become: yes
  tasks:
  - name: Creating user kubeconfig dir
    file:
      path: /home/ysung/.kube
      state: directory
      owner: ysung
      group: ysung
      recursive: yes
  - name: Fetching admin.conf
    tags: 
      - kubectl_fetch
    fetch:
      src: /etc/kubernetes/admin.conf
      dest: home/ysung/.kube/config
      flat: yes