- hosts: worker
  gather_facts: no
  become: yes
  tags: join
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tasks:
  - name: Generate join token
    shell: kubeadm token create --print-join-command
    register: join_command
    delegate_to: master-1
  - set_fact:
      kubeadm_join: "{{ join_command.stdout }}"
  - name: Run kubeadm join --worker
    shell: "{{ kubeadm_join }}" 
- hosts: all
  gather_facts: no
  become: yes
  tags: kubelet-extra
  tasks:
  - name: Copy kubelet-extra
    copy:
      src: kubelet
      dest: /etc/default/kubelet
  - name: restart kubelet
    systemd:
      name: kubelet
      state: restarted
      daemon_reload: yes